source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZYUIToolsPod_Example' do
  pod 'ZYUIToolsPod', :path => '../'

  target 'ZYUIToolsPod_Tests' do
    inherit! :search_paths

    
  end
end
